os: linux
language: c

before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update
    - sudo apt-get install criterion-dev

script:
    - make tests_run

compiler:
    - gcc
