version: 2.1
jobs:
  build:
    docker:
      - image: gcc
    steps:
      - run:
          command: |
            add-apt-repository -y ppa:snaipewastaken/ppa
            apt-get update
            apt-get install criterion-dev
            make tests_run