version: 2.1
jobs:
  build:
    docker:
      - image: gcc
    steps:
      - run:
          command: |
            sudo add-apt-repository -y ppa:snaipewastaken/ppa
            sudo apt-get update
            sudo apt-get install criterion-dev
            make tests_run